const restaurants = [
	{
		id: 1,
		nombre: "ABaC",
		localidad: "Barcelona",
		cocina: "Innovadora",
		precio: 200,
		url: "https://www.abacrestaurant.com/",
		estrellas: 3, 
        imgage: "/media/abac-restaurant.jpg",
	},
	{
		id: 2,
		nombre: "Akelarre",
		localidad: "San Sebastián",
		cocina: "Vasca",
		precio: 220,
		url: "https://www.akelarre.net/",
		estrellas: 3,
        imgage: "/media/akelare-restaurant.jpg",
	},
	{
		id: 3,
		nombre: "Amelia by Paulo Airaudo",
		localidad: "San Sebastián",
		cocina: "Contemporánea",
		precio: 180,
		url: "https://www.restaurantamelia.com/",
		estrellas: 2,
        imgage: "/media/amelia-by-paulo-restaurant.jpg",
	},
	{
		id: 4,
		nombre: "Aponiente",
		localidad: "El Puerto de Santa María",
		cocina: "Marinera",
		precio: 215,
		url: "https://www.aponiente.com/",
		estrellas: 3,
        imgage: "/media/aponiente-restaurant.webp",
	},
	{
		id: 5,
		nombre: "Arzak",
		localidad: "San Sebastián",
		cocina: "Vasca",
		precio: 210,
		url: "https://www.arzak.es/",
		estrellas: 3,
        imgage: "/media/arzak-restaurant.jpg",
	},
	{
		id: 6,
		nombre: "Atrio",
		localidad: "Cáceres",
		cocina: "Extremeña",
		precio: 190,
		url: "https://www.restauranteatrio.com/",
		estrellas: 3,
        imgage: "/media/atrio-restaurant.avif",
	},
	{
		id: 7,
		nombre: "Azurmendi",
		localidad: "Larrabetzu",
		cocina: "Vasca",
		precio: 220,
		url: "https://www.azurmendi.restaurant/",
		estrellas: 3,
        imgage: "/media/azurmendi-restaurant.jpg",
	},
	{
		id: 8,
		nombre: "Bardal",
		localidad: "Ronda",
		cocina: "Andaluza",
		precio: 165,
		url: "https://www.bardalrestaurant.com/",
		estrellas: 2,
        imgage: "/media/bordal-restaurant.jpg",
	},
	{
		id: 9,
		nombre: "BonAmb",
		localidad: "Jávea",
		cocina: "Mediterránea",
		precio: 150,
		url: "https://www.bonamb.com/",
		estrellas: 2,
        imgage: "/media/bonamb-restaurant.jpg",
	},
	{
		id: 10,
		nombre: "Cabaña Buenavista",
		localidad: "El Palmar",
		cocina: "Murciana",
		precio: 130,
		url: "https://www.cabanyabuenavista.com/",
		estrellas: 2,
        imgage: "/media/cabana-buenavista-restaurant.jpg",
	},
	{
		id: 11,
		nombre: "Casa Marcial",
		localidad: "Arriondas",
		cocina: "Asturiana",
		precio: 180,
		url: "https://www.casamarcial.com/",
		estrellas: 3,
        imgage: "/media/casa-marcial-restaurant.jpg",
	},
	{
		id: 12,
		nombre: "Cenador de Amós",
		localidad: "Villaverde de Pontones",
		cocina: "Cántabra",
		precio: 195,
		url: "https://www.cenadordeamos.com/",
		estrellas: 3,
        imgage: "/media/cenador-de-amos-restaurant.jpg",
	},
	{
		id: 13,
		nombre: "Cinc Sentits",
		localidad: "Barcelona",
		cocina: "Catalana",
		precio: 150,
		url: "https://www.cincsentits.com/",
		estrellas: 2,
        imgage: "/media/cinc-sentitis-restaurant.jpg",
	},
	{
		id: 14,
		nombre: "Coque",
		localidad: "Madrid",
		cocina: "Contemporánea",
		precio: 195,
		url: "https://www.coque.com/",
		estrellas: 2,
        imgage: "/media/coque-restaurant.jpg",
	},
	{
		id: 15,
		nombre: "DSTAgE",
		localidad: "Madrid",
		cocina: "Innovadora",
		precio: 175,
		url: "https://www.dstageconcept.com/",
		estrellas: 2,
        imgage: "/media/dstage-restaurant.webp",
	},
	{
		id: 16,
		nombre: "Disfrutar",
		localidad: "Barcelona",
		cocina: "Creativa",
		precio: 190,
		url: "https://www.disfrutarbarcelona.com/",
		estrellas: 3,
        imgage: "/media/disfrutar-restaurant.jpg",
	},
	{
		id: 17,
		nombre: "DiverXO",
		localidad: "Madrid",
		cocina: "Fusión",
		precio: 250,
		url: "https://www.diverxo.com/",
		estrellas: 3,
        imgage: "/media/diverxo-restaurant.webp",
	},
	{
		id: 18,
		nombre: "El Celler de Can Roca",
		localidad: "Girona",
		cocina: "Catalana",
		precio: 210,
		url: "https://www.cellercanroca.com/",
		estrellas: 3,
        imgage: "/media/celler-de-can-roca-restaurant.jpg",
	},
	{
		id: 19,
		nombre: "El Portal de Echaurren",
		localidad: "Ezcaray",
		cocina: "Riojana",
		precio: 160,
		url: "https://www.echaurren.com/",
		estrellas: 2,
        imgage: "/media/portal-de-echaurren-restaurant.jpg",
	},
	{
		id: 20,
		nombre: "Enoteca",
		localidad: "Barcelona",
		cocina: "Mediterránea",
		precio: 180,
		url: "https://www.enotecapacoperez.com/",
		estrellas: 2,
        imgage: "/media/enoteca-restaurant.jpg",
	},
	{
		id: 21,
		nombre: "L'Escaleta",
		localidad: "Cocentaina",
		cocina: "Valenciana",
		precio: 140,
		url: "https://www.lescaleta.com/",
		estrellas: 2,
        imgage: "/media/lescaleta-restaurant.jpeg",
	},
	{
		id: 22,
		nombre: "Lasarte",
		localidad: "Barcelona",
		cocina: "Vasca",
		precio: 230,
		url: "https://www.restaurantlasarte.com/",
		estrellas: 3,
        imgage: "/media/lasarte-restaurant.jpg",
	},
	{
		id: 23,
		nombre: "Maralba",
		localidad: "Almansa",
		cocina: "Manchega",
		precio: 120,
		url: "https://www.maralbarestaurante.com/",
		estrellas: 2,
        imgage: "/media/maralba-restaurant.jpg",
	},
	{
		id: 24,
		nombre: "Martín Berasategui",
		localidad: "Lasarte-Oria",
		cocina: "Vasca",
		precio: 250,
		url: "https://www.martinberasategui.com/",
		estrellas: 3,
        imgage: "/media/martin-berasategui-restaurant.jpg",
	},
	{
		id: 25,
		nombre: "Mugaritz",
		localidad: "Errenteria",
		cocina: "Innovadora",
		precio: 220,
		url: "https://www.mugaritz.com/",
		estrellas: 2,
        imgage: "/media/mugaritz-restaurant.webp",
	},
	{
		id: 26,
		nombre: "Noor",
		localidad: "Córdoba",
		cocina: "Andalusí",
		precio: 185,
		url: "https://www.noorrestaurant.es/",
		estrellas: 3,
        imgage: "/media/noor-restaurant.jpg",
	},
	{
		id: 27,
		nombre: "Paco Roncero Restaurante",
		localidad: "Madrid",
		cocina: "Contemporánea",
		precio: 180,
		url: "https://www.pacoroncero.com/",
		estrellas: 2,
        imgage: "/media/paco-roncero-restaurant.jpg",
	},
	{
		id: 28,
		nombre: "Quique Dacosta",
		localidad: "Dénia",
		cocina: "Innovadora",
		precio: 210,
		url: "https://www.quiquedacosta.com/",
		estrellas: 3,
        imgage: "/media/quique-dacosta-restaurant.jpg",
	},
	{
		id: 29,
		nombre: "Ramón Freixa",
		localidad: "Madrid",
		cocina: "Creativa",
		precio: 185,
		url: "https://www.ramonfreixa.com/",
		estrellas: 2,
        imgage: "/media/ramon-freixa-restaurant.jpg",
	},
	{
		id: 30,
		nombre: "Ricard Camarena Restaurant",
		localidad: "Valencia",
		cocina: "Mediterránea",
		precio: 175,
		url: "https://www.ricardcamarena.com/",
		estrellas: 2,
        imgage: "/media/ricard-camarena-restaurant.jpg",
	},
	{
		id: 31,
		nombre: "Skina",
		localidad: "Marbella",
		cocina: "Andaluza",
		precio: 180,
		url: "https://www.restauranteskina.com/",
		estrellas: 2,
        imgage: "/media/skina-restaurant.jpg",
	},
	{
		id: 32,
		nombre: "Smoked Room",
		localidad: "Madrid",
		cocina: "Fusión",
		precio: 200,
		url: "https://www.smokedroom.es/",
		estrellas: 2,
        imgage: "/media/smoked-room-restaurant.jpg",
	},
	{
		id: 33,
		nombre: "Voro",
		localidad: "Canyamel",
		cocina: "Balear",
		precio: 160,
		url: "https://www.vororestaurant.com/",
		estrellas: 2,
        imgage: "/media/voro-restaurant.jpg",
	},
];

